# Generated by Django 5.0.7 on 2024-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='Sample question', max_length=200),
            preserve_default=False,
        ),
    ]
