# Generated by Django 5.0.7 on 2024-12-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_choices_createdat_choices_updatedat_form_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
