# Generated by Django 5.0.7 on 2024-12-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_response_responseanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='code',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='responses',
            field=models.ManyToManyField(to='forms_app.responseanswer'),
        ),
    ]
