# Generated by Django 5.0.7 on 2024-12-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_response_code_response_responses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
